#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const out = `// @generated by scripts/write-version.mjs - do not edit\nexport const PLUGIN_VERSION = ${JSON.stringify(pkg.version)};\n`;
writeFileSync(join(root, "src/version.ts"), out);
